// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: issues.proto

package issues

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifecycleStateDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LifecycleStateDTO) Reset() {
	*x = LifecycleStateDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issues_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleStateDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleStateDTO) ProtoMessage() {}

func (x *LifecycleStateDTO) ProtoReflect() protoreflect.Message {
	mi := &file_issues_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleStateDTO.ProtoReflect.Descriptor instead.
func (*LifecycleStateDTO) Descriptor() ([]byte, []int) {
	return file_issues_proto_rawDescGZIP(), []int{0}
}

func (x *LifecycleStateDTO) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LifecycleStateDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LifecycleStateTransitionDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States []*LifecycleStateDTO `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
}

func (x *LifecycleStateTransitionDTO) Reset() {
	*x = LifecycleStateTransitionDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issues_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleStateTransitionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleStateTransitionDTO) ProtoMessage() {}

func (x *LifecycleStateTransitionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_issues_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleStateTransitionDTO.ProtoReflect.Descriptor instead.
func (*LifecycleStateTransitionDTO) Descriptor() ([]byte, []int) {
	return file_issues_proto_rawDescGZIP(), []int{1}
}

func (x *LifecycleStateTransitionDTO) GetStates() []*LifecycleStateDTO {
	if x != nil {
		return x.States
	}
	return nil
}

type LifecycleDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64                                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartState *LifecycleStateDTO                     `protobuf:"bytes,3,opt,name=startState,proto3" json:"startState,omitempty"`
	States     map[int32]*LifecycleStateTransitionDTO `protobuf:"bytes,4,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LifecycleDTO) Reset() {
	*x = LifecycleDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issues_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleDTO) ProtoMessage() {}

func (x *LifecycleDTO) ProtoReflect() protoreflect.Message {
	mi := &file_issues_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleDTO.ProtoReflect.Descriptor instead.
func (*LifecycleDTO) Descriptor() ([]byte, []int) {
	return file_issues_proto_rawDescGZIP(), []int{2}
}

func (x *LifecycleDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LifecycleDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LifecycleDTO) GetStartState() *LifecycleStateDTO {
	if x != nil {
		return x.StartState
	}
	return nil
}

func (x *LifecycleDTO) GetStates() map[int32]*LifecycleStateTransitionDTO {
	if x != nil {
		return x.States
	}
	return nil
}

type IssueDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string             `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	State       *LifecycleStateDTO `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	LifecycleId int64              `protobuf:"varint,5,opt,name=lifecycleId,proto3" json:"lifecycleId,omitempty"`
}

func (x *IssueDTO) Reset() {
	*x = IssueDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_issues_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueDTO) ProtoMessage() {}

func (x *IssueDTO) ProtoReflect() protoreflect.Message {
	mi := &file_issues_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueDTO.ProtoReflect.Descriptor instead.
func (*IssueDTO) Descriptor() ([]byte, []int) {
	return file_issues_proto_rawDescGZIP(), []int{3}
}

func (x *IssueDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IssueDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IssueDTO) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IssueDTO) GetState() *LifecycleStateDTO {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *IssueDTO) GetLifecycleId() int64 {
	if x != nil {
		return x.LifecycleId
	}
	return 0
}

var File_issues_proto protoreflect.FileDescriptor

var file_issues_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x37, 0x0a, 0x11, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4f,
	0x0a, 0x1b, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x54, 0x4f, 0x12, 0x30, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x44, 0x54, 0x4f, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x22,
	0x84, 0x02, 0x0a, 0x0c, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x44, 0x54, 0x4f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44,
	0x54, 0x4f, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x37,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x44, 0x54, 0x4f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x5d, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x54, 0x4f, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa2, 0x01, 0x0a, 0x08, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44,
	0x54, 0x4f, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x3b, 0x69, 0x73, 0x73, 0x75, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_issues_proto_rawDescOnce sync.Once
	file_issues_proto_rawDescData = file_issues_proto_rawDesc
)

func file_issues_proto_rawDescGZIP() []byte {
	file_issues_proto_rawDescOnce.Do(func() {
		file_issues_proto_rawDescData = protoimpl.X.CompressGZIP(file_issues_proto_rawDescData)
	})
	return file_issues_proto_rawDescData
}

var file_issues_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_issues_proto_goTypes = []interface{}{
	(*LifecycleStateDTO)(nil),           // 0: model.LifecycleStateDTO
	(*LifecycleStateTransitionDTO)(nil), // 1: model.LifecycleStateTransitionDTO
	(*LifecycleDTO)(nil),                // 2: model.LifecycleDTO
	(*IssueDTO)(nil),                    // 3: model.IssueDTO
	nil,                                 // 4: model.LifecycleDTO.StatesEntry
}
var file_issues_proto_depIdxs = []int32{
	0, // 0: model.LifecycleStateTransitionDTO.states:type_name -> model.LifecycleStateDTO
	0, // 1: model.LifecycleDTO.startState:type_name -> model.LifecycleStateDTO
	4, // 2: model.LifecycleDTO.states:type_name -> model.LifecycleDTO.StatesEntry
	0, // 3: model.IssueDTO.state:type_name -> model.LifecycleStateDTO
	1, // 4: model.LifecycleDTO.StatesEntry.value:type_name -> model.LifecycleStateTransitionDTO
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_issues_proto_init() }
func file_issues_proto_init() {
	if File_issues_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_issues_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleStateDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issues_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleStateTransitionDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issues_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_issues_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssueDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_issues_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_issues_proto_goTypes,
		DependencyIndexes: file_issues_proto_depIdxs,
		MessageInfos:      file_issues_proto_msgTypes,
	}.Build()
	File_issues_proto = out.File
	file_issues_proto_rawDesc = nil
	file_issues_proto_goTypes = nil
	file_issues_proto_depIdxs = nil
}
